spring:
  datasource:
    url: ${URL_DATABASE}
    username: postgres.hmsqylliuqfqkputilqw
    password: ${PASSWORD_DATABASE}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect