pdf:
  splitter:
    chunk-size: 512
    min-chunk-size-chars: 100
    min-chunk-length-to-embed: 50
    max-num-chunks: 5000
    keep-separator: true

vector:
  values:
    similarityThreshold: 0.60
    topK: 4
