spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/ai?options=-c%20TimeZone%3DAsia%2FKolkata
    username: ai
    password: ai
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect