Args = --initialize-at-build-time=ch.qos.logback \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=org.apache.logging.log4j \
       --initialize-at-build-time=org.apache.commons.logging \
       --initialize-at-build-time=org.springframework.core.SpringProperties
